---
- name: "Set node index"
  set_fact:
    node_index: "{{ groups[kaia_node_type].index(inventory_hostname) + 1 }}"

- name: "Read validator address for CN nodes"
  when: "'cn' in kaia_node_type"
  block:
    - name: "Read validator file"
      slurp:
        src: "{{ homi_output_dir }}/{{ kaia_node_type }}/keys/validator{{ node_index }}"
      register: validator_content
      delegate_to: localhost

    - name: "Set rewardbase from validator address"
      set_fact:
        kaia_conf_override: "{{ kaia_conf_override | default({}) | combine({'REWARDBASE': (validator_content.content | b64decode | from_json).Address}) }}"

- name: "Configuration - Template kaia configuration"
  become: yes
  template:
    src: "kaia.conf.j2"
    dest: "/etc/{{ kaia_daemon_name }}/conf/{{ kaia_daemon_name }}.conf"

- name: "Initialization - Copy static-nodes file"
  become: yes
  copy:
    src: "{{ homi_output_dir }}/{{ kaia_node_type }}/scripts/static-nodes{{ node_index }}.json"
    dest: "{{ kaia_conf.DATA_DIR }}/static-nodes.json"
  when: kaia_network is none

- name: "Initialization - Copy main-gridge.json"
  become: yes
  copy:
    src: "{{ homi_output_dir }}/bridge/main-bridges.json"
    dest: "{{ kaia_conf.DATA_DIR }}/main-bridges.json"
  when:
  - is_service_chain
  - kaia_bridge_enabled

- name: "Initialization - Copy nodekey file"
  become: yes
  copy:
    src: "{{ homi_output_dir }}/{{ kaia_node_type }}/keys/nodekey{{ node_index }}"
    dest: "{{ kaia_conf.DATA_DIR }}/nodekey"
  when: kaia_network is none

- name: Get checksum of local source of Genesis File
  stat:
    path: "{{ homi_output_dir }}/cn/scripts/genesis.json"
    checksum_algorithm: sha1
  register: source_stat
  delegate_to: localhost
  when:
  - is_service_chain == False
  - kaia_network is none

- name: Get checksum of local source of Genesis File(scn)
  stat:
    path: "{{ homi_output_dir }}/scn/scripts/genesis.json"
    checksum_algorithm: sha1
  register: source_stat_scn
  delegate_to: localhost
  when:
  - is_service_chain
  - kaia_network is none

- name: Get checksum of remote destination of Genesis file
  stat:
    path: "/etc/{{ kaia_daemon_name }}/genesis.json"
    checksum_algorithm: sha1
  register: dest_stat
  ignore_errors: true

- name: "Initialization - Copy Genesis File"
  become: yes
  copy:
    src: "{{ homi_output_dir }}/cn/scripts/genesis.json"
    dest: "/etc/{{ kaia_daemon_name }}/genesis.json"
  register: copy_genesis_file_result
  when:
  - is_service_chain == False
  - kaia_network is none
  - dest_stat.stat is not defined or source_stat.stat.checksum != dest_stat.stat.checksum

- name: "Initialization - Copy Genesis File(scn)"
  become: yes
  copy:
    src: "{{ homi_output_dir }}/scn/scripts/genesis.json"
    dest: "/etc/{{ kaia_daemon_name }}/genesis.json"
  register: copy_genesis_file_result_scn
  when:
  - is_service_chain
  - kaia_network is none
  - dest_stat.stat is not defined or source_stat_scn.stat.checksum != dest_stat.stat.checksum

- name: "Initialization - Init Kaia"
  become: yes
  shell:
    cmd: "rm -rf /var/k{{ kaia_node_type }}d/data/klay && rm -rf /var/k{{ kaia_node_type }}d/logs && mkdir -p /var/k{{ kaia_node_type }}d/logs"
  when:
  - kaia_network is none
  - copy_genesis_file_result is changed or copy_genesis_file_result_scn is changed

- name: "Initialization - Genensis"
  become: yes
  shell:
    cmd: "k{{ kaia_node_type }} init --datadir {{ kaia_conf.DATA_DIR }} /etc/{{ kaia_daemon_name }}/genesis.json"
  when:
  - kaia_network is none
  - copy_genesis_file_result is changed or copy_genesis_file_result_scn is changed
