---
- name: Install klaytn binary
  include_tasks: install.yml

- name: Copy required files
  include_tasks: copy_files.yml

- name: Start klaytn daemon
  become: yes
  systemd:
    name: "{{ klaytn_daemon_name }}" 
    state: restarted
    enabled: yes
    
