---
- name: Set build variables
  set_fact:
    git_url: "{{ deploy_options.kaia_build_remote_git_url | default(kaia_build_remote_git_url) }}"
    git_branch: "{{ deploy_options.kaia_build_remote_git_branch | default(kaia_build_remote_git_branch) }}"

- name: Calculate total builds
  set_fact:
    total_builds: "{{ [git_url | length if git_url is iterable and git_url is not string else 1, git_branch | length if git_branch is iterable and git_branch is not string else 1] | max }}"

- name: Create build identifiers for each build
  set_fact:
    build_identifiers: "{{ [] }}"

- name: Generate build identifier for each build
  set_fact:
    build_identifiers: "{{ build_identifiers + [(build_owner | first + '-' + build_branch)] }}"
  vars:
    current_git_url: "{{ git_url[item % git_url | length] if git_url is iterable and git_url is not string else git_url }}"
    build_owner: "{{ current_git_url | regex_search('[:/](?P<owner>[^/]+)/[^/]+$', '\\g<owner>') }}"
    build_branch: "{{ git_branch[item % git_branch | length] if git_branch is iterable and git_branch is not string else git_branch }}"
  loop: "{{ range(0, total_builds | int) | list }}"

- name: Build - Check directory exists
  ansible.builtin.stat:
    path: "{{ kaia_build_check_file_path }}-{{ build_identifiers[item] }}"
  register: kaia_build_check_file_stats
  loop: "{{ range(0, total_builds | int) | list }}"

- name: Build - Git checkout
  ansible.builtin.git:
    repo: "{{ git_url[item % git_url | length] if git_url is iterable and git_url is not string else git_url }}"
    dest: "{{ kaia_build_dir }}-{{ build_identifiers[item] }}"
    version: "{{ git_branch[item % git_branch | length] if git_branch is iterable and git_branch is not string else git_branch }}"
  loop: "{{ range(0, total_builds | int) | list }}"
  register: git_info

- name: Build - Check skipping compile
  set_fact:
    # Build required if:
    # - dir does not exist
    # - skip flag is false
    # - repo HEAD changed
    # - force compile is true
    kaia_build_required: >-
      {{ (kaia_build_required | default([])) + [ (
          kaia_build_check_file_stats.results[item].stat.exists == False
          or kaia_build_skip_if_exists == False
          or git_info.results[item].before != git_info.results[item].after
          or kaia_build_force_compile == True
      ) ] }}
  loop: "{{ range(0, total_builds | int) | list }}"

- name: Build - Create bin directory
  ansible.builtin.file:
    path: "{{ bin_dir }}-{{ build_identifiers[item] }}"
    state: directory
  when: kaia_build_required[item]
  loop: "{{ range(0, total_builds | int) | list }}"

- name: Build - Compile kaia binary
  ansible.builtin.command: |
    docker build --build-arg KLAYTN_STATIC_LINK=1 --build-arg DOCKER_BASE_IMAGE={{ kaia_build_docker_base_image }} -t {{ kaia_build_docker_builder_image }}-{{ item }} --output output .
  args:
    chdir: "{{ kaia_build_dir }}-{{ build_identifiers[item] }}"
  environment:
    DOCKER_BUILDKIT: 1
  when: kaia_build_required[item]
  loop: "{{ range(0, total_builds | int) | list }}"

- name: Build - Copy kaia binary files
  ansible.builtin.copy:
    dest: "{{ bin_dir }}-{{ build_identifiers[item[0]] }}"
    src: "{{ kaia_build_dir }}-{{ build_identifiers[item[0]] }}/output/klaytn-docker-pkg/bin/{{ item[1] }}"
    mode: preserve
  when: kaia_build_required[item[0]]
  with_nested:
    - "{{ range(0, total_builds | int) | list }}"
    - ['kbn', 'kcn', 'kpn', 'ken', 'kscn', 'kspn', 'ksen']

# There may be multiple git dirs to build different versions of kaia binaries,
# however we don't need to use different versions of homi to generate genesis and node keys.
# So we use the first git dir to build and run homi.
- name: Build - Compile homi binary locally
  ansible.builtin.command: |
    make homi
  args:
    chdir: "{{ kaia_build_dir }}-{{ build_identifiers[0] }}"
  when: kaia_build_required[0]

- name: Build - Copy homi binary
  ansible.builtin.copy:
    dest: "{{ bin_dir }}-{{ build_identifiers[0] }}/homi"
    src: "{{ kaia_build_dir }}-{{ build_identifiers[0] }}/build/bin/homi"
    mode: preserve

- name: Build - Create symbolic link to first bin directory
  ansible.builtin.file:
    src: "{{ bin_dir }}-{{ build_identifiers[0] }}"
    dest: "{{ bin_dir }}"
    state: link
  when: total_builds | int > 0

- name: Build - Copy kaia init.d script files
  ansible.builtin.copy:
    dest: "{{ bin_dir }}-{{ build_identifiers[item[0]] }}"
    src: "{{ kaia_build_dir }}-{{ build_identifiers[item[0]] }}/build/rpm/etc/init.d/{{ item[1] }}"
    mode: preserve
  when: kaia_build_required[item[0]]
  with_nested:
    - "{{ range(0, total_builds | int) | list }}"
    - ['kbnd', 'kcnd', 'kpnd', 'kend', 'kscnd', 'kspnd', 'ksend']

- name: Build - Creating an empty file for checking
  ansible.builtin.file:
    path: "{{ kaia_build_check_file_path }}-{{ build_identifiers[item] }}"
    state: touch
  when: kaia_build_required[item]
  loop: "{{ range(0, total_builds | int) | list }}"
