---
- hosts: localhost
  gather_facts: True
  roles:
  - { role: klayspray-defaults }
  - { role: local-init }
  tags:
  - localhost

- hosts: cn
  gather_facts: True
  vars:
    klaytn_node_type: cn
  roles:
  - { role: klayspray-defaults }
  - { role: node-init }

- hosts: pn
  gather_facts: True
  vars:
    klaytn_node_type: pn
  roles:
  - { role: klayspray-defaults }
  - { role: node-init }

- hosts: en
  gather_facts: True
  vars:
    klaytn_node_type: en
  roles:
  - { role: klayspray-defaults }
  - { role: node-init }

- hosts: monitor
  gather_facts: True
  roles:
  - { role: klayspray-defaults }
  - { role: setup-docker }
  - { role: monitor-init }
