---
- hosts: localhost
  gather_facts: True
  vars:
    klaytn_network_id: 9999
    klaytn_num_cn: 4
    klaytn_num_pn: 4
    klaytn_num_en: 1
  roles:
  - { role: klayspray-defaults }
  - { role: local-init }
  tags:
  - localhost

- hosts: cn
  gather_facts: True
  vars:
    klaytn_network_id: 9999
    klaytn_node_type: cn
    klaytn_conf_override:
      REWARDBASE: "0x46879cdc21832d6bd6b49081513fa3d965443075"
  roles:
  - { role: klayspray-defaults }
  - { role: node-init }

- hosts: pn
  gather_facts: True
  vars:
    klaytn_network_id: 9999
    klaytn_node_type: pn
  roles:
  - { role: klayspray-defaults }
  - { role: node-init }

- hosts: en
  gather_facts: True
  vars:
    klaytn_network_id: 9999
    klaytn_node_type: en
  roles:
  - { role: klayspray-defaults }
  - { role: node-init }

- hosts: monitor
  gather_facts: True
  roles:
  - { role: klayspray-defaults }
  - { role: setup-docker }
  - { role: monitor-init }
