---
- hosts: localhost
  gather_facts: True
  roles:
  - { role: kaiaspray-defaults }
  - { role: local-init }
  - role: build
    when: kaia_install_mode in ['build', 'build_remote']
  tags:
  - localhost

- hosts: cn,pn,en
  gather_facts: True
  strategy: free
  pre_tasks:
    - name: Set kaia_node_type variable
      set_fact:
        kaia_node_type: >-
          {{ ('cn' if 'cn' in group_names
              else 'pn' if 'pn' in group_names
              else 'en' if 'en' in group_names
              else 'unknown') | trim }}
    - name: Get node index
      set_fact:
        node_index: "{{ groups[kaia_node_type].index(inventory_hostname) }}"
    - name: Set configuration override
      set_fact:
        kaia_conf_override: "{{ 
          (cn_options.options[node_index] if 'cn' in group_names and cn_options.options is defined
           else pn_options.options[node_index] if 'pn' in group_names and pn_options.options is defined
           else en_options.options[node_index] if 'en' in group_names and en_options.options is defined
           else {}) | default({})
        }}"
  roles:
  - { role: kaiaspray-defaults }
  - { role: node-init }

- hosts: monitor
  gather_facts: True
  roles:
  - { role: kaiaspray-defaults }
  - { role: setup-docker }
  - { role: monitor-init }