---
- hosts: localhost
  gather_facts: True
  roles:
  - { role: klayspray-defaults }
  - { role: local-init }
  - { role: local-build, when: klaytn_install_mode == 'build' }
  tags:
  - localhost

- hosts: cn
  gather_facts: True
  vars:
    klaytn_node_type: cn
  roles:
  - { role: klayspray-defaults }
  - { role: node-init }

- hosts: pn
  gather_facts: True
  vars:
    klaytn_node_type: pn
  roles:
  - { role: klayspray-defaults }
  - { role: node-init }

- hosts: en
  gather_facts: True
  vars:
    klaytn_node_type: en
    klaytn_conf_override:
      RPC_ENABLE: 1
      RPC_API: klay,admin,personal,eth,web3,net
  roles:
  - { role: klayspray-defaults }
  - { role: node-init }

- hosts: monitor
  gather_facts: True
  roles:
  - { role: klayspray-defaults }
  - { role: setup-docker }
  - { role: monitor-init }
