---
- name: "Check nodekey exists"
  stat:
    path: "{{ homi_output_dir }}/{{ node.type }}/keys"
  register: check_nodekey_file

- name: "Generate {{ node.type }} data & genesis.json by Homi"
  shell: |
    {{ homi_bin }} setup local {{ homi_default_options }} --test-num {{ homi_test_account_num }} --cn-num {{ node.num }} --chainID {{ klaytn_network_id }} --network-id {{ klaytn_network_id }} -o {{ homi_output_dir }}/{{ node.type }}
  tags:
  - localhost
  when:
  - check_nodekey_file.stat.exists == False

- name: Convert and get validator data
  klay_validator:
    homi_output_dir: "{{ homi_output_dir }}"
    node_type: "{{ node.type }}"
    node_index: "{{ node_index | int }}"
    port: 32323
    public_ip: "{{ hostvars[item]['ansible_host'] }}"
    private_ip: "{{ hostvars[item]['ansible_private_host'] }}"
  register: validator_result
  loop: "{{ groups[node.type] }}"
  loop_control:
    index_var: node_index

- name: Generate validator file
  copy:
    content: "{{ item.validator }}"
    dest: "{{ homi_output_dir }}/{{ node.type }}/keys/validator{{ node_index | int + 1 }}"
  loop: "{{ validator_result.results }}"
  loop_control:
    index_var: node_index
