---
- name: "Check nodekey exists"
  stat:
    path: "{{ homi_output_dir }}/{{ node.type }}/keys"
  register: check_nodekey_file

- name: "Generate {{ node.type }} data & genesis.json by Homi"
  shell: |
    {{ homi_bin }} setup local {{ homi_default_options }} --cn-num {{ node.num }} --chainID {{ klaytn_network_id }} --network-id {{ klaytn_network_id }} -o {{ homi_output_dir }}/{{ node.type }}
  tags:
  - localhost
  when:
  - check_nodekey_file.stat.exists == False

- name: "Modify {{ node.type }} validator file"
  replace:
    path: "{{ homi_output_dir }}/{{ node.type }}/keys/validator{{ idx + 1 }}"
    regexp: "([0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+\\:\\d{1,5}\\?)"
    replace: "{{ hostvars[item]['ansible_host'] }}:32323?"
  loop: "{{ groups[node.type] }}"
  loop_control:
    index_var: idx
  tags:
  - localhost
