---
- name: "Make configuration directory"
  become: yes
  file:
    path: "{{ grafana_provisioning_dir }}"
    state: "directory"
  tags:
  - grafana

- name: "Copy static dashboard files"
  become: yes
  copy:
    src: "files/grafana/{{ item }}"
    dest: "{{ grafana_provisioning_dir }}"
  loop:
  - datasources
  - dashboards
  tags:
  - grafana

- name: "Run grafana docker"
  become: yes
  docker_container:
    name: grafana
    image: grafana/grafana
    volumes:
    - "{{ grafana_provisioning_dir }}:/etc/grafana/provisioning"
    network_mode: host
    restart_policy: always
    state: started
    detach: yes
  tags:
  - grafana

- debug:
    msg: "Grafana is listening on :{{ grafana_port }}"
  tags:
  - grafana
